'use strict';
const $=id=>document.getElementById(id),pct=v=>(100*v).toFixed(1)+'%';
const C={text:'#e7eee5',muted:'#99aa9c',green:'#c2e899',teal:'#6fc7bc',gold:'#e9be75',line:'#2b372e'};
let graph,nodes=new Map(),incoming=new Map(),outgoing=new Map(),selected=10360,visible=[],drawEdges=[],flow=true,zoom=1,pan=[0,0],drag=null,partnerLimit=80;
let shape=null,shapeId=null,angle=.2,tilt=.2,shapeZoom=1,rotate=false,shapeDrag=null;
let membrane=null,cellIndex=0,cellPlaying=true,cellLast=0,sdr=null,sdrFlow=true,panel='anatomy';
function stroke(g,points,color,width=1){if(!points.length)return;g.beginPath();points.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.strokeStyle=color;g.lineWidth=width;g.stroke();}
function label(n){return n?.instance||n?.type||String(n?.bodyId||'Unknown');}
function coords(event,c){const r=c.getBoundingClientRect();return [(event.clientX-r.left)*c.width/r.width,(event.clientY-r.top)*c.height/r.height];}
function setPanel(id){panel=id;for(const p of document.querySelectorAll('.tab-panel'))p.hidden=p.id!==id;for(const b of document.querySelectorAll('[data-panel]'))b.classList.toggle('active',b.dataset.panel===id);if(id==='cell'&&!membrane)runCell();if(id==='sdr'&&!sdr)runSDR();}
for(const b of document.querySelectorAll('[data-panel]'))b.onclick=()=>setPanel(b.dataset.panel);
$('go-cell').onclick=()=>{setPanel('cell');$('cell').scrollIntoView({behavior:'smooth'});};
function search(){const q=$('search').value.toLowerCase();$('search-results').replaceChildren();let matches=0;for(const n of nodes.values()){if((String(n.bodyId)+' '+label(n)+' '+(n.role||'')).toLowerCase().includes(q)){matches++;if(matches<=40){const b=document.createElement('button');b.textContent=`${label(n)} · ${n.bodyId}`;b.onclick=()=>select(n.bodyId);$('search-results').append(b);}}}if(matches>40){const p=document.createElement('p');p.className='hint';p.textContent=`${matches} matches; refine to see more.`;$('search-results').append(p);}}
$('search').oninput=search;
function layout(){const min=Math.max(1,Number($('min-edge').value)||1),limit=Number($('partner-count').value);const ins=(incoming.get(selected)||[]).filter(e=>e[2]>=min).sort((a,b)=>b[2]-a[2]),outs=(outgoing.get(selected)||[]).filter(e=>e[2]>=min).sort((a,b)=>b[2]-a[2]);visible=[{id:selected,x:600,y:330,kind:'selected'}];const exists=new Set([selected]);for(const [list,kind,side] of [[ins,'in',-1],[outs,'out',1]]){const items=list.slice(0,limit);items.forEach((e,i)=>{const id=kind==='in'?e[0]:e[1];if(exists.has(id))return;exists.add(id);const theta=-1.15+2.3*(i+.5)/Math.max(items.length,1);visible.push({id,x:600+side*(170+Math.cos(theta)*220),y:330+Math.sin(theta)*280,kind});});}const lookup=new Map(visible.map(n=>[n.id,n]));drawEdges=[...ins,...outs].filter(e=>lookup.has(e[0])&&lookup.has(e[1])).map(e=>({a:lookup.get(e[0]),b:lookup.get(e[1]),weight:e[2]}));$('graph-count').textContent=`Showing ${visible.length} real cells and ${drawEdges.length} measured directed edges. ${ins.length} incoming / ${outs.length} outgoing connections match the filter within the loaded subsets.`;partners();}
function partners(){const isIn=$('direction').value==='in',q=$('partner-filter').value.toLowerCase(),min=Math.max(1,Number($('min-edge').value)||1);const rows=[...(isIn?incoming:outgoing).get(selected)||[]].filter(e=>e[2]>=min).sort((a,b)=>b[2]-a[2]).filter(e=>{const n=nodes.get(e[isIn?0:1]);return (label(n)+' '+n.bodyId).toLowerCase().includes(q);});$('partners').replaceChildren();for(const e of rows.slice(0,partnerLimit)){const id=e[isIn?0:1],tr=document.createElement('tr'),td=document.createElement('td'),b=document.createElement('button');b.textContent=label(nodes.get(id));b.onclick=()=>select(id);td.append(b);tr.append(td);for(const v of [id,e[2]]){const d=document.createElement('td');d.textContent=v.toLocaleString();tr.append(d);}$('partners').append(tr);}$('more-partners').hidden=rows.length<=partnerLimit;$('more-partners').textContent=`Show more (${Math.min(partnerLimit,rows.length)}/${rows.length})`;}
$('more-partners').onclick=()=>{partnerLimit+=100;partners();};$('direction').onchange=()=>{partnerLimit=80;partners();};$('partner-filter').oninput=()=>{partnerLimit=80;partners();};$('min-edge').onchange=layout;$('partner-count').onchange=layout;
async function select(id){selected=id;partnerLimit=80;const n=nodes.get(id);$('selected-name').textContent=label(n);$('selected-meta').textContent=`Body ${id} · ${n.role||n.superclass} · ${n.subset} subset${n.nt?' · predicted transmitter: '+n.nt:''}`;$('cell-identity').textContent=`Selected: ${label(n)} (${id}).`;
 if(membrane){membrane=null;$('cell-status').textContent='Selection changed; run the same generic membrane model for this identity.';if(panel==='cell')runCell();}
 zoom=1;pan=[0,0];layout();shape=null;shapeId=id;$('skeleton-state').textContent='Downloading official reconstructed skeleton…';$('skeleton-source').removeAttribute('href');drawShape();try{const r=await fetch('/api/skeleton?id='+id),s=await r.json();if(shapeId!==id)return;if(!r.ok)throw Error(s.error);shape=s;const pts=s.points;const ranges=[1,2,3].map(k=>{let min=Infinity,max=-Infinity;for(const p of pts){min=Math.min(min,p[k]);max=Math.max(max,p[k]);}return [min,max];});shape.center=ranges.map(r=>(r[0]+r[1])/2);shape.extent=Math.max(...ranges.map(r=>r[1]-r[0]));shape.lookup=new Map(pts.map(p=>[p[0],p]));shapeZoom=1;$('skeleton-state').textContent=`${pts.length.toLocaleString()} reconstructed points · span ${shape.extent.toFixed(1)} µm`;$('skeleton-source').href=s.source;drawShape();}catch(e){if(shapeId===id){$('skeleton-state').textContent=e.message;drawShape();}}}
function drawNetwork(now){const c=$('network'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);g.save();g.translate(c.width/2+pan[0],c.height/2+pan[1]);g.scale(zoom,zoom);g.translate(-c.width/2,-c.height/2);for(const e of drawEdges){const color=e.a.id===selected?C.teal:C.green;stroke(g,[[e.a.x,e.a.y],[e.b.x,e.b.y]],color+'55',Math.min(4,.4+Math.log1p(e.weight)/3)/Math.sqrt(zoom));const dx=e.b.x-e.a.x,dy=e.b.y-e.a.y,a=Math.atan2(dy,dx);const ax=e.a.x+dx*.73,ay=e.a.y+dy*.73;g.beginPath();g.moveTo(ax,ay);g.lineTo(ax-7*Math.cos(a-.5),ay-7*Math.sin(a-.5));g.lineTo(ax-7*Math.cos(a+.5),ay-7*Math.sin(a+.5));g.fillStyle=color;g.fill();if(flow){const f=(now/1800+(e.weight%17)/17)%1;g.beginPath();g.arc(e.a.x+dx*f,e.a.y+dy*f,2.8/Math.sqrt(zoom),0,Math.PI*2);g.fillStyle=color;g.fill();}}
 for(const n of visible){g.beginPath();g.arc(n.x,n.y,n.id===selected?13:5,0,Math.PI*2);g.fillStyle=n.kind==='selected'?C.gold:n.kind==='in'?C.green:C.teal;g.fill();if(zoom>1.4||n.id===selected||visible.length<45){g.font=(n.id===selected?'16':'11')+'px sans-serif';g.fillStyle=C.text;g.textAlign=n.kind==='in'?'right':'left';g.fillText(label(nodes.get(n.id)),n.x+(n.kind==='in'?-11:16),n.y+4);}}g.restore();g.textAlign='left';g.font='13px sans-serif';g.fillStyle=C.muted;g.fillText('Incoming → selected → outgoing · structural animation',20,28);}
const net=$('network');net.onwheel=e=>{e.preventDefault();zoom=Math.max(.4,Math.min(8,zoom*Math.exp(-e.deltaY*.001)));};net.onpointerdown=e=>{net.setPointerCapture(e.pointerId);drag={start:coords(e,net),pan:[...pan],moved:false};};net.onpointermove=e=>{if(!drag)return;const p=coords(e,net);if(Math.hypot(p[0]-drag.start[0],p[1]-drag.start[1])>4)drag.moved=true;pan=[drag.pan[0]+p[0]-drag.start[0],drag.pan[1]+p[1]-drag.start[1]];};net.onpointerup=e=>{if(drag&&!drag.moved){const p=coords(e,net),x=(p[0]-net.width/2-pan[0])/zoom+net.width/2,y=(p[1]-net.height/2-pan[1])/zoom+net.height/2;const n=visible.reduce((best,n)=>Math.hypot(n.x-x,n.y-y)<(best?.d??16/zoom)?{n,d:Math.hypot(n.x-x,n.y-y)}:best,null);if(n)select(n.n.id);}drag=null;};$('zoom-in').onclick=()=>zoom=Math.min(8,zoom*1.4);$('zoom-out').onclick=()=>zoom=Math.max(.4,zoom/1.4);$('reset-view').onclick=()=>{zoom=1;pan=[0,0];};$('flow').onclick=()=>{flow=!flow;$('flow').textContent=flow?'Pause edge directions':'Animate edge directions';};
function drawShape(){const c=$('skeleton'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);if(!shape){g.fillStyle=C.muted;g.font='15px sans-serif';g.fillText($('skeleton-state').textContent,25,45);return;}const scale=440/Math.max(shape.extent,1)*shapeZoom;const project=p=>{const x=p[1]-shape.center[0],y=p[2]-shape.center[1],z=p[3]-shape.center[2],u=x*Math.cos(angle)+z*Math.sin(angle),zz=-x*Math.sin(angle)+z*Math.cos(angle);return [c.width/2+u*scale,c.height/2+(y*Math.cos(tilt)-zz*Math.sin(tilt))*scale];};g.beginPath();for(const p of shape.points){const parent=shape.lookup.get(p[4]);if(parent){g.moveTo(...project(parent));g.lineTo(...project(p));}}g.strokeStyle=C.green;g.lineWidth=.8;g.stroke();g.fillStyle=C.muted;g.font='13px monospace';g.fillText(`Body ${shape.bodyId} · orthographic 3D rotation`,20,28);const bar=50*scale;stroke(g,[[30,c.height-35],[30+bar,c.height-35]],C.text,2);g.fillText('50 µm',30,c.height-15);}
const sk=$('skeleton');sk.onpointerdown=e=>{sk.setPointerCapture(e.pointerId);shapeDrag={p:coords(e,sk),a:angle,t:tilt};};sk.onpointermove=e=>{if(shapeDrag){const p=coords(e,sk);angle=shapeDrag.a+(p[0]-shapeDrag.p[0])*.008;tilt=shapeDrag.t+(p[1]-shapeDrag.p[1])*.008;drawShape();}};sk.onpointerup=()=>shapeDrag=null;sk.onwheel=e=>{e.preventDefault();shapeZoom=Math.min(8,Math.max(.3,shapeZoom*Math.exp(-e.deltaY*.001)));drawShape();};$('rotate').onclick=()=>{rotate=!rotate;$('rotate').textContent=rotate?'Pause rotation':'Rotate shape';};
async function runCell(){const b=$('run-cell');b.disabled=true;$('cell-status').textContent='Solving voltage and channel-gating equations…';try{const r=await fetch('/api/membrane',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({body_id:selected,current:Number($('current').value),inhibition:Number($('inhibition').value),context:Number($('context').value),block_na:$('block-na').checked})}),d=await r.json();if(!r.ok)throw Error(d.error);membrane=d;cellIndex=0;cellPlaying=true;cellLast=0;$('cell-scrub').max=d.time_ms.length-1;$('cell-status').textContent=`${d.spike_times_ms.length} modeled spikes. Channel parameters are generic, not fitted to this neuron.`;$('spike-count').textContent=d.spike_times_ms.length;$('cell-play').textContent='Pause';drawCell();}catch(e){$('cell-status').textContent=e.message;}finally{b.disabled=false;}}
$('run-cell').onclick=runCell;$('context').oninput=()=>$('context-count').textContent=$('context').value+' / 8';$('cell-play').onclick=()=>{cellPlaying=!cellPlaying;cellLast=0;$('cell-play').textContent=cellPlaying?'Pause':'Play';};$('cell-scrub').oninput=()=>{cellIndex=Number($('cell-scrub').value);cellPlaying=false;$('cell-play').textContent='Play';drawCell();};
function drawCell(){if(!membrane)return;const r=membrane,i=cellIndex,t=r.time_ms[i],v=r.voltage_mv[i],c=$('cell-diagram'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);$('cell-time').textContent=t.toFixed(2)+' ms';$('cell-scrub').value=i;$('voltage').textContent=v.toFixed(1)+' mV';$('ina').textContent=r.sodium_current[i].toFixed(1);$('ik').textContent=r.potassium_current[i].toFixed(1);g.font='15px sans-serif';g.fillStyle=C.muted;g.fillText('Hypothetical dendritic segment',30,32);for(let k=0;k<8;k++){const x=40+(k%4)*44,y=65+Math.floor(k/4)*36;g.fillStyle=k<r.parameters.context?C.green:C.line;g.fillRect(x,y,25,18);stroke(g,[[x+12,y+18],[240,160]],C.line,1);}stroke(g,[[240,160],[385,160]],r.plateau_current?C.green:C.line,8);g.fillStyle=C.muted;g.fillText('Coincidence ≥ 4 → plateau',25,240);g.fillText('Current pulse →',235,305);stroke(g,[[340,295],[425,210]],C.gold,3);g.beginPath();g.ellipse(525,175,125,112,0,0,Math.PI*2);g.fillStyle='#1b2a20';g.fill();g.strokeStyle=v>0?C.gold:C.green;g.lineWidth=4;g.stroke();g.textAlign='center';g.fillStyle=C.text;g.font='28px Georgia';g.fillText(v.toFixed(1)+' mV',525,180);g.font='13px sans-serif';g.fillStyle=C.muted;g.fillText('membrane patch',525,205);g.textAlign='left';
 for(const [y,sign,color,title,gate] of [[115,-1,C.green,'Na⁺ · activation / inactivation',r.m[i]**3*r.h[i]],[245,1,C.teal,'K⁺ · delayed outward current',r.n[i]**4]]){const magnitude=Math.min(1,Math.abs(sign<0?r.sodium_current[i]:r.potassium_current[i])/200);stroke(g,[[660,y],[900,y]],color,3);g.fillStyle=color;g.font='14px sans-serif';g.fillText(title,700,y-27);g.font='12px monospace';g.fillText(`open-gate factor ${gate.toFixed(3)}`,710,y+28);for(let k=0;k<6;k++){const f=(t/2+k/6)%1,x=sign<0?900-f*240:660+f*240;g.globalAlpha=.2+.8*magnitude;g.beginPath();g.arc(x,y,4+3*magnitude,0,Math.PI*2);g.fill();}g.globalAlpha=1;}const plot=$('voltage-chart'),ctx=plot.getContext('2d'),W=plot.width,H=plot.height;ctx.clearRect(0,0,W,H);const x=time=>60+time/60*(W-90),yv=value=>235-(value+90)/140*195,yg=value=>305-value*50;ctx.font='12px monospace';ctx.fillStyle=C.muted;for(const value of [-80,-40,0,40]){stroke(ctx,[[60,yv(value)],[W-30,yv(value)]],C.line);ctx.fillText(String(value),18,yv(value)+4);}for(const value of [0,10,20,30,40,50,60])ctx.fillText(String(value),x(value)-6,H-10);stroke(ctx,r.time_ms.map((t,j)=>[x(t),yv(r.voltage_mv[j])]),C.text,2);for(const [key,color] of [['m',C.green],['h',C.gold],['n',C.teal]])stroke(ctx,r.time_ms.map((t,j)=>[x(t),yg(r[key][j])]),color,1.5);stroke(ctx,[[x(t),25],[x(t),H-30]],C.gold,1);ctx.fillText('mV',14,18);ctx.fillText('gates 0–1',10,254);ctx.fillText('Time (ms)',W/2,H-10);}
async function runSDR(){const b=$('run-sdr');b.disabled=true;$('sdr-status').textContent='Training on examples; testing frozen weights…';try{const r=await fetch('/api/sdr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({encoding:$('sdr-encoding').value,condition:$('sdr-condition').value,seed:Number($('sdr-seed').value),epochs:Number($('sdr-epochs').value)})}),d=await r.json();if(!r.ok)throw Error(d.error);sdr=d;updateReadout();const [a,b]=d.sdr.examples,inter=(x,y)=>x.filter(i=>y.includes(i)).length;$('pn-overlap').textContent=inter(a.pn_active,b.pn_active)+' / '+a.pn_active.length;const intersection=inter(a.kc_active,b.kc_active);$('kc-overlap').textContent=pct(intersection/(new Set([...a.kc_active,...b.kc_active]).size||1));$('sdr-verdict').textContent=`Plastic classifier: ${pct(d.summary.test_accuracy)} unseen accuracy. Alternative learned number readouts: ${d.decoder_comparison.map(x=>x.name+' '+pct(x.test_accuracy)).join('; ')}. These ridge decoders are separate engineering baselines, fitted once on training examples; they are not the biological plasticity model.`;$('sdr-status').textContent='Complete. Inspect overlaps and compare the alternative decoders.';$('export-sdr').disabled=false;}catch(e){$('sdr-status').textContent=e.message;}finally{b.disabled=false;}}
function updateReadout(){if(!sdr)return;const r=$('readout').value==='classifier'?sdr.summary:sdr.decoder_comparison[Number($('readout').value)];$('sdr-train').textContent=pct(r.train_accuracy);$('sdr-test').textContent=pct(r.test_accuracy);}
$('readout').onchange=updateReadout;
$('run-sdr').onclick=runSDR;$('sdr-animate').onclick=()=>{sdrFlow=!sdrFlow;$('sdr-animate').textContent=sdrFlow?'Pause workflow':'Animate workflow';};$('export-sdr').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(sdr,null,2)],{type:'application/json'}));a.download='sdr-experiment.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
function drawSDR(now){if(!sdr)return;const c=$('sdr-flow'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);const stage=sdrFlow?Math.floor(now/1400)%3:2;function grid(x,y,n,active,columns,size,color){const a=new Set(active);for(let i=0;i<n;i++){g.fillStyle=a.has(i)?color:'#253228';g.fillRect(x+(i%columns)*size,y+Math.floor(i/columns)*size,size-1,size-1);}}g.font='17px sans-serif';g.fillStyle=C.text;g.fillText('1 · Synthetic PN input',30,35);g.fillText('2 · Measured PN → KC + 2% winners',440,35);g.fillText('3 · Learned output',920,35);const examples=sdr.sdr.examples;examples.forEach((r,j)=>{const y=80+j*240;g.fillStyle=C.muted;g.font='15px monospace';g.fillText(`${r.a} + ${r.b}`,30,y-15);grid(30,y,sdr.sdr.pn_cells,r.pn_active,32,10,j?C.teal:C.green);grid(440,y,sdr.sdr.kc_cells,r.kc_active,81,5,j?C.teal:C.green);stroke(g,[[365,y+65],[425,y+65]],stage===1?C.gold:C.line,3);stroke(g,[[865,y+65],[905,y+65]],stage===2?C.gold:C.line,3);const p=sdr.problems.find(p=>p.a===r.a&&p.b===r.b);g.font='38px Georgia';g.fillStyle=C.text;const prediction=$('readout').value==='classifier'?p.prediction:sdr.decoder_comparison[Number($('readout').value)].rounded_predictions[sdr.problems.indexOf(p)];g.fillText(String(prediction),960,y+70);g.font='13px sans-serif';g.fillStyle=C.muted;g.fillText(`true sum ${p.correct}`,930,y+100);g.fillText(p.split==='train'?'taught pair':'unseen pair',930,y+123);});g.fillStyle=C.muted;g.font='13px sans-serif';g.fillText('Each KC square maps to a measured cell ID. Bit layout is a grid for inspection, not anatomical position.',30,595);}
async function loadBench(){try{const r=await fetch('/api/sdr-benchmark');if(!r.ok)throw Error('Saved SDR benchmark unavailable');const b=await r.json(),keys=[...new Set(b.runs.map(r=>r.parameters.encoding+' / '+r.parameters.condition))];for(const key of keys){const rows=b.runs.filter(r=>r.parameters.encoding+' / '+r.parameters.condition===key);for(const variant of ['classifier',0,1]){const values=rows.map(r=>variant==='classifier'?r.summary:r.decoder_comparison[variant]);const tr=document.createElement('tr');for(const value of [key+(variant==='classifier'?' · plastic classifier':variant===0?' · KC ridge decoder':' · direct SDR ridge baseline'),pct(values.reduce((s,r)=>s+r.train_accuracy,0)/values.length),pct(values.reduce((s,r)=>s+r.test_accuracy,0)/values.length)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}$('sdr-controls').append(tr);}}}catch(e){$('sdr-status').textContent=e.message;}}
let lastFrame=0;function tick(now){if(now-lastFrame>35){lastFrame=now;if(panel==='anatomy'){drawNetwork(now);if(rotate&&shape){angle+=.008;drawShape();}}if(panel==='cell'&&membrane){if(cellPlaying){if(!cellLast)cellLast=now;cellIndex=(cellIndex+Math.max(1,Math.floor((now-cellLast)/6)))%membrane.time_ms.length;cellLast=now;}drawCell();}if(panel==='sdr')drawSDR(now);}requestAnimationFrame(tick);}
async function init(){try{const r=await fetch('/api/explorer');if(!r.ok)throw Error('Could not load measured subsets');graph=await r.json();for(const n of graph.nodes){nodes.set(n.bodyId,n);incoming.set(n.bodyId,[]);outgoing.set(n.bodyId,[]);}for(const e of graph.edges){incoming.get(e[1]).push(e);outgoing.get(e[0]).push(e);}$('scope').textContent=`${nodes.size.toLocaleString()} cells, ${graph.edges.length.toLocaleString()} edges loaded. ${graph.scope}`;search();select(selected);loadBench();}catch(e){$('selected-name').textContent=e.message;}}
init();requestAnimationFrame(tick);
