'use strict';
const $=id=>document.getElementById(id),pct=x=>(100*x).toFixed(1)+'%';
const names={intact:'Measured pathway',no_learning:'No learning',shuffled_labels:'Shuffled teaching labels',shuffled_wiring:'Shuffled PN → KC',silence_kc:'KC silenced'};
let lesson;
function ask(){if(!lesson)return;const a=Number($('a').value),b=Number($('b').value);if(!Number.isInteger(a)||!Number.isInteger(b)||a<0||a>9||b<0||b>9){$('explanation').textContent='Enter whole numbers from 0 to 9.';return;}const r=lesson.problems.find(r=>r.a===a&&r.b===b);$('answer').textContent=`${a} + ${b} → ${r.prediction}`;$('explanation').textContent=`${r.split==='train'?'Previously taught':'Never taught'} · ${r.prediction===r.correct?'Correct':'Incorrect; correct answer is '+r.correct} · model confidence ${pct(r.confidence)}${r.teacher_label!==null&&lesson.parameters.condition==='shuffled_labels'?' · supplied teacher label '+r.teacher_label:''}.`;}
function chart(){const c=$('math-chart'),g=c.getContext('2d'),W=c.width,H=c.height;g.clearRect(0,0,W,H);const rows=lesson.history,max=Math.max(1,lesson.parameters.epochs),x=e=>60+e/max*(W-90),y=a=>H-45-a*(H-80);g.font='12px monospace';g.fillStyle='#99aa9c';for(let i=0;i<=4;i++){g.beginPath();g.moveTo(60,y(i/4));g.lineTo(W-30,y(i/4));g.strokeStyle='#2b372e';g.stroke();g.fillText(String(i*25),18,y(i/4)+4);g.fillText(String(Math.round(max*i/4)),x(max*i/4)-5,H-25);}for(const [key,color] of [['train_accuracy','#c2e899'],['test_accuracy','#e9be75']]){g.beginPath();rows.forEach((r,i)=>i?g.lineTo(x(r.epoch),y(r[key])):g.moveTo(x(r.epoch),y(r[key])));g.strokeStyle=color;g.lineWidth=3;g.stroke();for(const r of rows){g.beginPath();g.arc(x(r.epoch),y(r[key]),2,0,Math.PI*2);g.fillStyle=color;g.fill();}}g.fillStyle='#99aa9c';g.fillText('Accuracy %',8,16);g.fillText('Training epochs',W/2-50,H-5);}
function show(){const s=lesson.summary;$('train-score').textContent=pct(s.train_accuracy);$('test-score').textContent=pct(s.test_accuracy);$('teacher-score').textContent=pct(s.teacher_accuracy);$('verdict').textContent=`${names[lesson.parameters.condition]}: ${Math.round(s.train_accuracy*80)}/80 taught questions and ${Math.round(s.test_accuracy*20)}/20 unseen questions answered correctly. ${s.train_accuracy-s.test_accuracy>.3?'The large gap indicates memorization without comparable transfer.':'Compare unseen performance with the controls before inferring a learned rule.'}`;$('baseline').textContent=`Always guessing the most frequent training answer (${lesson.baseline.majority_answer}) scores ${pct(lesson.baseline.majority_test_accuracy)} on this held-out set.`;const m=$('matrix');m.replaceChildren();const head=t=>{const d=document.createElement('div');d.className='axis';d.textContent=t;m.append(d);};head('+');for(let b=0;b<10;b++)head(b);for(let a=0;a<10;a++){head(a);for(let b=0;b<10;b++){const r=lesson.problems[a*10+b],button=document.createElement('button');button.className='cell'+(r.split==='unseen'?' held':'')+(r.prediction===r.correct?' correct':'');button.textContent=r.prediction;button.title=`${a} + ${b}: predicted ${r.prediction}, correct ${r.correct}; ${r.split}`;button.setAttribute('aria-label',button.title);button.onclick=()=>{$('a').value=a;$('b').value=b;ask();};m.append(button);}}chart();ask();$('export').disabled=false;}
$('ask').onclick=ask;
$('teach').onclick=async()=>{$('teach').disabled=true;$('status').textContent='Teaching on the training set, then testing frozen weights…';try{const r=await fetch('/api/math',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({condition:$('condition').value,seed:Number($('seed').value),epochs:Number($('epochs').value),learning_rate:Number($('rate').value)})});const data=await r.json();if(!r.ok)throw Error(data.error);lesson=data;show();$('status').textContent='Lesson complete. Click an outlined cell to quiz an unseen pair.';}catch(e){$('status').textContent=e.message;}finally{$('teach').disabled=false;}};
$('export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(lesson,null,2)],{type:'application/json'}));a.download=`addition-${lesson.parameters.condition}-seed${lesson.parameters.seed}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
async function init(){$('teach').click();try{const r=await fetch('/api/math-benchmark');if(!r.ok)throw Error('Control benchmark unavailable');const b=await r.json();for(const condition of b.conditions){const runs=b.runs.filter(r=>r.parameters.condition===condition);const row=document.createElement('tr');for(const v of [names[condition],...['train_accuracy','test_accuracy','teacher_accuracy'].map(k=>pct(runs.reduce((s,r)=>s+r.summary[k],0)/runs.length))]){const td=document.createElement('td');td.textContent=v;row.append(td);}$('controls').append(row);}}catch(e){$('status').textContent=e.message;}}
init();
