'use strict';
const $=id=>document.getElementById(id),pct=x=>(100*x).toFixed(1)+'%',fmt=(x,n=3)=>Number(x).toFixed(n);
const colors=['#c2e899','#6fc7bc','#e9be75','#a9abed'],ink='#e7eee5',muted='#99aa9c',line='#2b372e';
let result=null,benchmark=null,frame=0,playing=true,last=0,selected=0,positions=[],model,scene,edges=[],counts=new Map();
const sig=x=>1/(1+Math.exp(-Math.max(-40,Math.min(40,x))));
function text(g,s,x,y,size=14,color=muted){g.font=size+'px sans-serif';g.fillStyle=color;g.fillText(s,x,y);}
function path(g,pts,color,width=1){if(!pts.length)return;g.beginPath();pts.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.strokeStyle=color;g.lineWidth=width;g.stroke();}
function dot(g,x,y,r,color){g.beginPath();g.arc(x,y,r,0,Math.PI*2);g.fillStyle=color;g.fill();}
function activityColor(v){const a=Math.min(1,Math.abs(v)),base=[35,48,40],hi=v>=0?[194,232,153]:[137,162,241];return `rgb(${base.map((b,i)=>Math.round(b+(hi[i]-b)*a)).join(',')})`;}
function choose(){if(!result)return;model=result.models.find(m=>m.kind===$('model').value);scene=result.demonstrations[Number($('scene').value)||0];edges=model.learned_edges;selected=Math.min(selected,model.nodes-1);$('node').replaceChildren();for(let i=0;i<model.nodes;i++){const n=result.circuit.nodes[i],o=document.createElement('option');o.value=i;o.textContent=model.kind==='dense_rnn'?`Hidden unit ${i+1}`:`${n.type} · ${n.bodyId} · column ${n.column+1}`;$('node').append(o);}$('node').value=selected;$('network-title').textContent=model.kind==='dense_rnn'?`${model.nodes} conventional hidden units`:`${model.nodes} real cells · ${model.state_size} internal state${model.state_size>1?'s':''} each`;$('network-note').textContent=model.kind==='dense_rnn'?'Dense hidden units have no anatomical identity. All-to-all recurrence and learned input mixing; selected unit shown in gold.':`${edges.length.toLocaleString()} allowed directed edges. Graph positions group annotated columns and types, not neuron shapes. Green = positive state, violet = negative; each half of a node shows one state. Gold marks the selected cell. Highlighted edges are its incoming/outgoing messages.`;if(model.eye){const e=model.eye;$('network-note').textContent+=` Trainable eye: adaptation a=${fmt(e.adaptation_a,2)}, k=${fmt(e.adaptation_k,2)}, gain ${fmt(e.gain,2)}; each column keeps ${fmt(e.projection_self_mean,2)} of its own signal and mixes ${fmt(e.projection_other_mean_abs,3)} per allowed other column (${e.projection_allowed_entries} allowed entries). Node inputs below are the eye's output, not raw samples.`;}comparison();draw();}
function bind(r){result=r;counts=new Map(r.circuit.edges.map(([a,b,w])=>[a+':'+b,w]));$('scene').replaceChildren();for(const d of r.demonstrations){const o=document.createElement('option');o.value=d.index;o.textContent=`Test clip ${d.index+1} / ${r.test_size}`;$('scene').append(o);}selected=r.circuit.nodes.findIndex(n=>n.type==='Tm1');$('protocol').textContent=`Seed ${r.seed} · ${r.epochs} epochs · ${r.train_size} train / ${r.validation_size} validation / ${r.test_size} test clips. Test clips are independent generated sequences.`;$('load-status').textContent=`Loaded ${r.circuit.nodes.length} measured cells. Every displayed prediction is from an unseen test clip; the first 12 clips are available for inspection.`;choose();}
$('model').onchange=choose;$('scene').onchange=()=>{frame=0;choose();};$('node').onchange=()=>{selected=Number($('node').value);draw();};$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Pause replay':'Play replay';};$('frame').oninput=()=>{frame=Number($('frame').value);playing=false;$('play').textContent='Play replay';draw();};
function drawRetina(){const c=$('retina'),g=c.getContext('2d'),p=scene.scene;g.clearRect(0,0,c.width,c.height);const X=35,Y=45,W=405;for(let iy=0;iy<60;iy++)for(let ix=0;ix<60;ix++){const x=(ix/59-.5)*3,y=(iy/59-.5)*3,dx=x-(p.cx+p.vx*frame),dy=y-(p.cy+p.vy*frame),r=p.radius*Math.exp(p.growth*frame),v=Math.exp(-(dx*dx+dy*dy)/(2*r*r))*(.65+.35*Math.cos(p.frequency*dx+p.phase)*Math.cos(p.frequency*dy-p.phase));const gray=Math.round(20+v*220);g.fillStyle=`rgb(${gray},${gray},${gray})`;g.fillRect(X+ix*W/60,Y+iy*W/60,W/60+1,W/60+1);}text(g,'Synthetic image · local field',X,25,15);text(g,'19 directional samples',580,25,15);for(let i=0;i<result.circuit.columns.length;i++){const q=result.circuit.columns[i],sx=X+(q.x/3+.5)*W,sy=Y+(q.y/3+.5)*W;g.strokeStyle='#c2e89999';g.beginPath();g.arc(sx,sy,4,0,Math.PI*2);g.stroke();const x=745+q.x*150,y=245+q.y*150,value=(scene.retina[frame][i]+1)/2,v=Math.round(value*220+20);g.beginPath();for(let j=0;j<6;j++){const a=Math.PI/3*j+Math.PI/6;j?g.lineTo(x+35*Math.cos(a),y+35*Math.sin(a)):g.moveTo(x+35*Math.cos(a),y+35*Math.sin(a));}g.closePath();g.fillStyle=`rgb(${v},${v},${v})`;g.fill();g.strokeStyle=line;g.stroke();g.textAlign='center';text(g,String(i+1),x,y+4,11,v>135?'#132015':'#aab7ad');g.textAlign='left';}text(g,'Input is intensity; no velocity or hazard label is provided.',470,447,12);}
function arrow(g,dx,dy,color){const cx=230,cy=160,x=cx+dx*115,y=cy+dy*115,a=Math.atan2(y-cy,x-cx);path(g,[[cx,cy],[x,y]],color,3);path(g,[[x-12*Math.cos(a-.5),y-12*Math.sin(a-.5)],[x,y],[x-12*Math.cos(a+.5),y-12*Math.sin(a+.5)]],color,3);}
function drawPrediction(){const c=$('prediction'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);path(g,[[70,160],[390,160]],line);path(g,[[230,20],[230,285]],line);const p=model.predictions[scene.index],t=scene.target;arrow(g,t[0],t[1],colors[1]);arrow(g,p[0],p[1],colors[0]);text(g,'True motion',25,315,13,colors[1]);text(g,'Predicted motion',215,315,13,colors[0]);text(g,`vx ${fmt(p[0]*.075)} · vy ${fmt(p[1]*.075)} field units/frame`,40,28,12);$('hazard').textContent=pct(sig(p[2]));$('truth').textContent=t[2]?'Hazard':'No hazard';}
function drawNetwork(){const c=$('network'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);const state=model.demo_activity[scene.index][frame],dense=model.kind==='dense_rnn';positions=[];if(dense){for(let i=0;i<model.nodes;i++)positions.push([100+(i%12)*105,85+Math.floor(i/12)*105]);for(let i=0;i<model.nodes;i++)if(i!==selected)path(g,[positions[i],positions[selected]],line,1);text(g,'Each unit receives a learned mixture of all 19 sensory inputs.',30,35,16);}else{const types=result.circuit.types;for(let i=0;i<types.length;i++)text(g,types[i],20,63+i*44,15);for(let i=0;i<19;i++)text(g,String(i+1),142+i*64,28,12);text(g,'Column',20,28,12);for(const n of result.circuit.nodes)positions.push([147+n.column*64,59+types.indexOf(n.type)*44]);for(const [a,b,w] of edges){if(a===selected||b===selected)continue;path(g,[positions[a],positions[b]],'#34473a25',.6);}for(const [a,b,w] of edges){if(a!==selected&&b!==selected)continue;const A=positions[a],B=positions[b],color=b===selected?colors[1]:colors[2];path(g,[A,B],color+'99',1.4);const x=A[0]+.7*(B[0]-A[0]),y=A[1]+.7*(B[1]-A[1]),ang=Math.atan2(B[1]-A[1],B[0]-A[0]);path(g,[[x-6*Math.cos(ang-.5),y-6*Math.sin(ang-.5)],[x,y],[x-6*Math.cos(ang+.5),y-6*Math.sin(ang+.5)]],color,1.5);}}
 for(let i=0;i<positions.length;i++){const [x,y]=positions[i],r=dense?16:8;for(let d=0;d<model.state_size;d++){g.beginPath();g.moveTo(x,y);g.arc(x,y,r,d*Math.PI*2/model.state_size,(d+1)*Math.PI*2/model.state_size);g.closePath();g.fillStyle=activityColor(state[i][d]);g.fill();}if(i===selected){g.beginPath();g.arc(x,y,r+4,0,Math.PI*2);g.strokeStyle=colors[2];g.lineWidth=2;g.stroke();}if(dense)text(g,String(i+1),x+22,y+4,12);}text(g,'Activity scale −1 … 0 … +1 · recurrent computation, not action potentials',20,537,12);}
$('network').onclick=e=>{if(!model)return;const c=$('network'),r=c.getBoundingClientRect(),x=(e.clientX-r.left)*c.width/r.width,y=(e.clientY-r.top)*c.height/r.height;let best=-1,dist=20;positions.forEach((p,i)=>{const d=Math.hypot(p[0]-x,p[1]-y);if(d<dist){dist=d;best=i;}});if(best>=0){selected=best;$('node').value=best;draw();}};
function drawNode(){const dense=model.kind==='dense_rnn',n=result.circuit.nodes[selected],trace=model.demo_activity[scene.index],cur=trace[frame][selected],prev=frame?trace[frame-1]:Array.from({length:model.nodes},()=>Array(model.state_size).fill(0));$('node-title').textContent=dense?`Hidden unit ${selected+1}`:`${n.type} · body ${n.bodyId}`;$('node-subtitle').textContent=dense?'A learned hidden unit with no biological identity.':`Annotated column ${n.column+1} · hex (${n.hex.join(', ')}) · ${model.state_size} recurrent state variable${model.state_size>1?'s':''}`;const c=$('node-chart'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);for(const v of [-1,0,1]){const y=135-v*90;path(g,[[50,y],[860,y]],line);text(g,String(v),14,y+4,12);}for(let d=0;d<model.state_size;d++){path(g,[[50,135],...trace.map((t,i)=>[50+(i+1)*80,135-t[selected][d]*90])],colors[d],3);text(g,`State ${d+1}: ${fmt(cur[d])}`,50+d*260,270,15,colors[d]);}path(g,[[50+(frame+1)*80,25],[50+(frame+1)*80,240]],colors[2],1);text(g,'Sequence start → 10 frames',50,22,13);$('messages').replaceChildren();$('node-terms').replaceChildren();
 if(dense){$('node-explanation').textContent='Dense baseline: all-to-all recurrent messages, learned input mixing and a scalar local state. See the matched-parameter comparison below.';$('edge-note').textContent='Dense connections are learned engineering parameters, not anatomical synapses.';return;}
 $('edge-note').textContent=model.kind==='shuffled_vector'?'Rewired connections are synthetic. Synapse counts are not assigned; click a source to follow its message.':'Sorted by absolute incoming message at this frame; click a source to follow it.';$('node-explanation').textContent='new state = 0.5 × previous state + 0.5 × tanh(neighbor sum + local memory + sensory drive + bias)';const nm=model.node_models,msgs=edges.filter(e=>e[1]===selected).map(([a,b,w])=>({a,w,msg:w*prev[a][0]})).sort((a,b)=>Math.abs(b.msg)-Math.abs(a.msg));for(const msg of msgs){const source=result.circuit.nodes[msg.a],tr=document.createElement('tr'),td=document.createElement('td'),b=document.createElement('button');b.textContent=`${source.type} · ${source.bodyId}`;b.onclick=()=>{selected=msg.a;$('node').value=selected;draw();};td.append(b);tr.append(td);for(const value of [model.kind==='shuffled_vector'?'—':(counts.get(source.bodyId+':'+n.bodyId)??'—'),fmt(msg.w),fmt(msg.msg)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}$('messages').append(tr);}
 for(let d=0;d<model.state_size;d++){const neighbor=msgs.reduce((s,m)=>s+m.w*prev[m.a][d],0),local=prev[selected].reduce((s,v,i)=>s+v*nm.U[selected][i][d],0),input=(model.eye_input_demo?model.eye_input_demo[scene.index][frame][n.column]:scene.retina[frame][n.column])*nm.G[selected][d],bias=nm.b[selected][d],tr=document.createElement('tr');for(const value of [d+1,fmt(neighbor),fmt(local),fmt(input),fmt(bias),fmt(cur[d])]){const td=document.createElement('td');td.textContent=value;tr.append(td);}$('node-terms').append(tr);}
}
function comparison(){if(!result)return;$('comparison').replaceChildren();for(const m of result.models){const tr=document.createElement('tr');if(m.kind===model.kind)tr.className='selected-row';for(const value of [m.name,m.parameters.toLocaleString(),fmt(m.initial_test.motion_rmse,4),fmt(m.test.motion_rmse,4),fmt(m.test.direction_error_deg,1)+'°',pct(m.test.hazard_accuracy),fmt(m.test.hazard_brier)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}$('comparison').append(tr);}const b=result.constant_baseline;$('baseline').textContent=`Training-mean predictor: motion RMSE ${fmt(b.motion_rmse,4)}, hazard accuracy ${pct(b.hazard_accuracy)}, Brier ${fmt(b.hazard_brier)}. Test hazard prevalence ${pct(result.hazard_prevalence)}. Motion units are normalized field units/frame. Lower Brier means better probability predictions.`;drawLearning();}
function drawLearning(){const c=$('learning'),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);const all=result.models.flatMap(m=>m.history.map(h=>h.validation.motion_rmse)),max=Math.max(.05,...all)*1.1;for(let i=0;i<4;i++){const val=max*i/3,y=230-val/max*190;path(g,[[60,y],[875,y]],line);text(g,fmt(val),5,y+4,12);}result.models.forEach((m,i)=>{path(g,m.history.map(h=>[60+h.epoch/Math.max(1,result.epochs)*815,230-h.validation.motion_rmse/max*190]),colors[i],2);text(g,['Measured · 1 state','Measured · 2 states','Rewired · 2 states','Dense RNN'][i],50+i*210,280,12,colors[i]);});text(g,'Validation motion RMSE',60,22,13);text(g,`${result.epochs} epochs`,775,250,12);}
function draw(){if(!result)return;$('frame').value=frame;$('frame-label').textContent=`${frame+1} / 10`;drawRetina();drawPrediction();drawNetwork();drawNode();}
function animate(now){if(playing&&result&&now-last>500){last=now;frame=(frame+1)%10;draw();}requestAnimationFrame(animate);}requestAnimationFrame(animate);
async function bench(){try{const r=await fetch('/api/vision-benchmark');if(!r.ok)throw Error('Saved benchmark unavailable');benchmark=await r.json();$('benchmark').replaceChildren();for(const kind of ['graph_scalar','graph_vector','shuffled_vector','dense_rnn','eye_graph','eye_dense']){const rows=benchmark.runs.map(r=>r.models.find(m=>m.kind===kind));if(rows.some(m=>!m))continue;const mean=fn=>rows.reduce((s,m)=>s+fn(m),0)/rows.length,tr=document.createElement('tr');for(const value of [rows[0].name,fmt(mean(m=>m.test.motion_rmse),4),fmt(mean(m=>m.test.direction_error_deg),1)+'°',pct(mean(m=>m.test.hazard_accuracy)),fmt(mean(m=>m.test.hazard_brier),4),kind==='dense_rnn'?'Not evaluated':fmt(mean(m=>m.edges_ablated_test.motion_rmse),4),kind.startsWith('eye_')?fmt(mean(m=>m.eye_reset_test.motion_rmse),4):'—']){const td=document.createElement('td');td.textContent=value;tr.append(td);}$('benchmark').append(tr);}}catch(e){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=7;td.textContent=e.message;tr.append(td);$('benchmark').append(tr);}}
$('train').onclick=async()=>{const b=$('train');b.disabled=true;$('train-status').textContent='Training six recurrent networks, then evaluating held-out scenes…';try{const r=await fetch('/api/vision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seed:Number($('seed').value),epochs:Number($('epochs').value)})}),d=await r.json();if(!r.ok)throw Error(d.error);bind(d);$('train-status').textContent=`Finished in ${fmt(d.elapsed_seconds,1)} s. New test results are shown above. Saved three-seed comparison is unchanged.`;}catch(e){$('train-status').textContent=e.message;}finally{b.disabled=false;}};
$('export').onclick=()=>{if(!result)return;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(result)],{type:'application/json'}));a.href=url;a.download=`vision-experiment-${result.seed}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
(async()=>{try{const r=await fetch('/api/vision-example');if(!r.ok)throw Error('No saved experiment. Use “Train all four networks” below.');bind(await r.json());}catch(e){$('load-status').textContent=e.message;}bench();})();
